import { useEffect, useState } from "react";
import AddOutlined from "@mui/icons-material/AddOutlined";
import DeleteOutlineOutlined from "@mui/icons-material/DeleteOutlineOutlined";
import EditOutlined from "@mui/icons-material/EditOutlined";
import SearchOutlined from "@mui/icons-material/SearchOutlined";
import { apiFetch } from "../lib/api";
import { ErrorMessage, inputClass, Modal, PageHeader } from "./TeacherUI";

const blank={code:"",text:"",topic:"",difficulty:"easy",points:1,options:["","","",""],correctOption:0};
export default function QuestionBank(){
 const [items,setItems]=useState([]),[search,setSearch]=useState(""),[difficulty,setDifficulty]=useState(""),[error,setError]=useState(""),[form,setForm]=useState(blank),[editingId,setEditingId]=useState(""),[open,setOpen]=useState(false);
 const load=()=>apiFetch(`/api/questions?size=50&search=${encodeURIComponent(search)}&difficulty=${difficulty}`).then((data)=>setItems(data.items)).catch((e)=>setError(e.message));
 useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[search,difficulty]);
 const edit=(item)=>{setEditingId(item.id);setForm({...item,options:[...item.options]});setOpen(true)};
 const submit=async(e)=>{e.preventDefault();try{await apiFetch(editingId?`/api/questions/${editingId}`:"/api/questions",{method:editingId?"PUT":"POST",body:JSON.stringify(form)});setOpen(false);setForm(blank);setEditingId("");load()}catch(err){setError(err.message)}};
 const remove=async(item)=>{if(!confirm(`Delete ${item.code}?`))return;try{await apiFetch(`/api/questions/${item.id}`,{method:"DELETE"});load()}catch(err){setError(err.message)}};
 return <><PageHeader title="Question Bank" description="Create, search, update and organize exam questions." action={<button onClick={()=>{setForm(blank);setEditingId("");setOpen(true)}} className="flex items-center gap-2 rounded bg-blue-700 px-4 py-3 text-sm font-bold text-white"><AddOutlined fontSize="small"/>Add Question</button>}/><ErrorMessage message={error}/>
 <section className="mb-5 grid gap-3 rounded border border-slate-300 bg-white p-4 md:grid-cols-[2fr_1fr]"><label className="relative"><SearchOutlined className="absolute left-3 top-3 text-slate-400" fontSize="small"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search by code or question" className="w-full rounded border border-slate-300 py-2.5 pl-10 pr-3"/></label><select value={difficulty} onChange={(e)=>setDifficulty(e.target.value)} className="rounded border border-slate-300 px-3"><option value="">All difficulties</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></section>
 <section className="overflow-hidden rounded border border-slate-300 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr>{["Code","Question","Topic","Difficulty","Correct answer","Points","Actions"].map((x)=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{items.map((item)=><tr key={item.id} className="border-t"><td className="px-4 py-4 font-semibold text-blue-700">{item.code}</td><td className="max-w-xs px-4">{item.text}</td><td className="px-4">{item.topic}</td><td className="px-4 capitalize">{item.difficulty}</td><td className="px-4 text-green-700">{item.options[item.correctOption]}</td><td className="px-4">{item.points}</td><td className="px-4"><div className="flex gap-2"><button aria-label="Edit item" title="Edit" onClick={()=>edit(item)} className="rounded border border-blue-300 p-2 text-blue-700"><EditOutlined fontSize="small"/></button><button aria-label="Delete item" title="Delete" onClick={()=>remove(item)} className="rounded border border-red-300 p-2 text-red-600"><DeleteOutlineOutlined fontSize="small"/></button></div></td></tr>)}</tbody></table></div></section>
 {open&&<Modal title={editingId?"Edit Question":"Add Question"} onClose={()=>setOpen(false)}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Code<input required value={form.code} onChange={(e)=>setForm({...form,code:e.target.value.toUpperCase()})} className={inputClass}/></label><label className="text-sm font-semibold">Topic<input required value={form.topic} onChange={(e)=>setForm({...form,topic:e.target.value})} className={inputClass}/></label><label className="text-sm font-semibold sm:col-span-2">Question<textarea required value={form.text} onChange={(e)=>setForm({...form,text:e.target.value})} className={inputClass}/></label>{form.options.map((option,index)=><label key={index} className="text-sm font-semibold">Option {String.fromCharCode(65+index)}<input required value={option} onChange={(e)=>{const options=[...form.options];options[index]=e.target.value;setForm({...form,options})}} className={inputClass}/></label>)}<label className="text-sm font-semibold">Correct option<select value={form.correctOption} onChange={(e)=>setForm({...form,correctOption:Number(e.target.value)})} className={inputClass}>{form.options.map((_,i)=><option key={i} value={i}>Option {String.fromCharCode(65+i)}</option>)}</select></label><label className="text-sm font-semibold">Difficulty<select value={form.difficulty} onChange={(e)=>setForm({...form,difficulty:e.target.value})} className={inputClass}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label className="text-sm font-semibold">Points<input required type="number" min="0.5" step="0.5" value={form.points} onChange={(e)=>setForm({...form,points:Number(e.target.value)})} className={inputClass}/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded border px-4 py-2">Cancel</button><button className="rounded bg-blue-700 px-4 py-2 font-bold text-white">Save Question</button></div></form></Modal>}</>;
}

