import { useEffect, useState } from "react";
import SearchOutlined from "@mui/icons-material/SearchOutlined";
import { apiFetch } from "../lib/api";
import { ErrorMessage, PageHeader } from "./TeacherUI";
export default function TeacherAttempts(){
 const [items,setItems]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>apiFetch(`/api/attempts?search=${encodeURIComponent(search)}&status=${status}`).then((d)=>setItems(d.items)).catch((e)=>setError(e.message)),200);return()=>clearTimeout(timer)},[search,status]);
 return <><PageHeader title="Student Attempts" description="Review exam participation, progress and submitted scores."/><ErrorMessage message={error}/><section className="mb-5 grid gap-3 rounded border bg-white p-4 md:grid-cols-[2fr_1fr]"><label className="relative"><SearchOutlined className="absolute left-3 top-3 text-slate-400" fontSize="small"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search student or exam" className="w-full rounded border border-slate-300 py-2.5 pl-10 pr-3"/></label><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded border border-slate-300 px-3"><option value="">All statuses</option><option value="in_progress">In progress</option><option value="submitted">Submitted</option></select></section><section className="overflow-hidden rounded border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-100"><tr>{["Student","Exam","Attempt","Started","Submitted","Score","Status"].map((x)=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{items.map((item)=><tr key={item.id} className="border-t"><td className="px-4 py-4"><b className="block">{item.studentName||"Unknown"}</b><small className="text-slate-500">{item.studentEmail}</small></td><td className="px-4"><b className="block text-blue-700">{item.examTitle||"Deleted exam"}</b><small>{item.examCode}</small></td><td className="px-4">{item.attemptNumber}</td><td className="px-4">{item.startedAt?new Date(item.startedAt).toLocaleString():"-"}</td><td className="px-4">{item.submittedAt?new Date(item.submittedAt).toLocaleString():"-"}</td><td className="px-4 font-bold">{item.percentage==null?"-":`${item.percentage}%`}</td><td className="px-4 capitalize">{item.status?.replace("_"," ")}</td></tr>)}{!items.length&&<tr><td colSpan="7" className="p-8 text-center text-slate-500">No attempts found.</td></tr>}</tbody></table></div></section></>;
}
